// Code generated by staticerize, DO NOT EDIT.
//
// input parameters: /tmp/go-build426970817/b001/exe/staticerize -in testtext.txt -out example.go -pkg main
package main

// generated using staticerize from file testtext.txt
const testtext = `fgjklsdjkflsd
fsfsdf
fgjklsdjkflsd


fsdfsa
fgjklsdjkflsdgas
g

g

g
fgjklsdjkflsddfs
54
56
56 
467
b
 y65
  e`
